// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgbUeM3gEYDDKR1Mh_n3B0hc-5SQNm8E',
    appId: '1:627794157926:web:9d7d38b8dc2497a6abe8a7',
    messagingSenderId: '627794157926',
    projectId: 'qrcafe-428a3',
    authDomain: 'qrcafe-428a3.firebaseapp.com',
    databaseURL: 'https://qrcafe-428a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrcafe-428a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtjQj9a3-hkH0_KXyAZYD1VOAlN5L5Psc',
    appId: '1:627794157926:android:268dd7ee3a0484fdabe8a7',
    messagingSenderId: '627794157926',
    projectId: 'qrcafe-428a3',
    databaseURL: 'https://qrcafe-428a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrcafe-428a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90hkR9MIqR3_DF5xSmp0P6Fo2I01RQv4',
    appId: '1:627794157926:ios:85e6499bd29e14e3abe8a7',
    messagingSenderId: '627794157926',
    projectId: 'qrcafe-428a3',
    databaseURL: 'https://qrcafe-428a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrcafe-428a3.appspot.com',
    iosClientId: '627794157926-27vd64kkq761lfkl3hphjo43joi6bktj.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90hkR9MIqR3_DF5xSmp0P6Fo2I01RQv4',
    appId: '1:627794157926:ios:85e6499bd29e14e3abe8a7',
    messagingSenderId: '627794157926',
    projectId: 'qrcafe-428a3',
    databaseURL: 'https://qrcafe-428a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrcafe-428a3.appspot.com',
    iosClientId: '627794157926-27vd64kkq761lfkl3hphjo43joi6bktj.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
